TIMEZONE = "Asia/Kolkata"
DEFAULT_TIME_FORMAT = "%d-%m-%Y %H:%M:%S"
TIME_STAMP_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
DEFAULT_TIME_FORMAT_WITH_FS = "%d/%m/%Y %H:%M:%S"
TIME_FORMAT_YYY_MM_DD = "%Y-%m-%d %H:%M:%S"
TIME_FORMAT_DD_MM_YY_HH_MM = "%d/%m/%Y %H:%M"
YMDTHMS_FORMAT = "%Y-%m-%dT%H:%M:%S"

auth_endpoint_name = "/ilens_api/ilens_config/login-check"
auth_error_msg = "Unable to process request- "
